blank_issues_enabled: true
contact_links:
  - name: â“ Question
    url: https://github.com/transitive-bullshit/agentic/discussions/new?category=Q%26A
    about: Got a (non-bug related) question? Ask the community for help!
  - name: ğŸ’¡ Feature Request
    url: https://github.com/transitive-bullshit/agentic/discussions/new?category=Ideas
    about: Share ideas for new features with the community.
